services:
  # Base de datos PostgreSQL
  - type: pserv
    name: merci-db
    env: postgresql
    plan: free
    ipAllowList: []

  # Backend API
  - type: web
    name: backby-tree
    env: node
    plan: free
    buildCommand: npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://arbol-de-prediccion.onrender.com
      - key: DATABASE_URL
        fromService:
          name: merci-db
          type: pserv
          property: connectionString

  # Frontend
  - type: web
    name: arbol-de-prediccion
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://backby-tree.onrender.com/api 